FROM openjdk:8u232-jdk-slim 
RUN mkdir /opt/tomcat
ADD http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz /tmp/
RUN cd /tmp && tar xvfz apache-tomcat-8.5.50.tar.gz
RUN mv /tmp/apache-tomcat-8.5.50/* /opt/tomcat/
EXPOSE 8080
ENTRYPOINT ["/opt/tomcat/bin/catalina.sh", "run"]
